### ISSUE TITLE
Running a node on Ubuntu 16.04

### ISSUE THREAD

**Issue by decryptoed** [fairlayer/fair#14]
What are the steps/commands to run a testnet node on a Linux platform? Below are the steps I have tried (with Node v9.11.1 via nvm) .

1)
a. git clone https://github.com/fairlayer/fair && cd fair
b. ./install
c. node fair
Resulting command line : 
Reading db  data/onchain/db.sqlite
Reading and syncing offchain db: sqlite
Loading K data
   [Error] Unable to read "./data/onchain/k.json", quitting
(node:9994) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './data/onchain/k.json'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at loadKFile (/home/decryptoed/FairLayer/fair/src/fair.js:81:19)
    at startFairlayer (/home/decryptoed/FairLayer/fair/src/fair.js:162:7)
    at <anonymous>
(node:9994) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9994) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2) 
a. git clone https://github.com/fairlayer/fair && cd fair
b. ./deploy
Resulting command line : 
yarn install v1.9.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 4.14s.

> @ build /home/decryptoed/FairLayer/fair
> parcel build wallet/index.html

⏳  Building bootstrap.min.css...
Node#moveTo was deprecated. Use Container#append.
✨  Built in 9.99s.

dist/main.795f3128.js                  299.45 KB    28.89s
dist/chart.63163a79.js                 145.45 KB     3.26s
dist/bootstrap.min.20abbb74.css        118.87 KB     520ms
dist/notyf.d8b8ab42.js                   2.96 KB     1.60s
dist/notyf.efdd8d3b.css                  2.11 KB      77ms
dist/reddit.c46e82d0.svg                 2.05 KB      58ms
dist/main.5648710d.css                    1020 B      63ms
dist/index.html                           1013 B     400ms
dist/github.01dc78db.svg                   898 B      58ms
dist/twitter.75ac189e.svg                  830 B      58ms
dist/atelier-dune-dark.a1c3758f.css        587 B      85ms
dist/medium.3464a892.svg                   552 B      58ms
dist/notyf.d8b8ab42.map                      0 B     1.63s
dist/chart.63163a79.map                      0 B     3.30s
dist/main.bd03407c.map                       0 B    28.91s
./prod: line 33: pm2: command not found
Reading db  data/onchain/db.sqlite
Reading and syncing offchain db: mysql
(node:10242) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Utils.Promise.tap.then.catch.err (/home/decryptoed/FairLayer/fair/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:139:19)
    at tryCatcher (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/decryptoed/FairLayer/fair/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
(node:10242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10242) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
./prod: line 38: pm2: command not found

**Comment by homakov** [comment]
I know it might be confusing, but you cannot install it from the repo. Repo is a generic code and not attached to any network. `node fair` only works when there's a data dir. You can run `./simulate` for local private net.

To join open testnet you, as a user, navigate to https://fairlayer.com/#install and run the snippet. That should install everything automatically.

Will add it to README.

**Comment by decryptoed** [comment]
Okay, thanks! I managed to get the testnet node to work.

I wanted to note that when I ran the snippet, I got the following error related to xdg-open : 

Reading db  data/onchain/db.sqlite
Reading and syncing offchain db: sqlite
Loading K data
Loading PK data
  ⠟ Open http://127.0.0.1:8001/#?auth_code=82415ea53306f3b8616b46138b5a015f5611419c08a4fe3b20cda102fa340c9a in your browser

  ⠟ Welcome to Fair REPL!
  ⠟ oops { Error: spawn /home/decryptoed/fair/lib/xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/decryptoed/fair/lib/xdg-open',
  path: '/home/decryptoed/fair/lib/xdg-open',
  spawnargs: 
   [ 'http://127.0.0.1:8001/#?auth_code=82415ea53306f3b8616b46138b5a015f5611419c08a4fe3b20cda102fa340c9a' ] }
   [Error] Bye
oops 0

I managed to solve this by copying fair/node_modules/opn/xdg-open to fair/lib/ .

**Comment by homakov** [comment]
@decryptoed 


Oh yes, there is no instruction notes for server side install yet. `opn` only works on desktop. So you were supposed to pass `-s/--slient` to disable opn which would not raise this error. Will note that too! And available any time if you have questions on UX/etc.

**Comment by homakov** [comment]
P.S. the server just got dead, apparently after trying to register you (user id = 11). Will investigate why.

Testnet is commonly reloaded so the old node stops working and you'd need to just get a new install every time. If you want to play around best way imo is ./simulate for private net.
